services:
  - type: web
    name: alien-hairdresser-salon
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: node dist/server.js
    nodeVersion: 18.x
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
